// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMVC.NetApp.Data;

#nullable disable

namespace MyMVC.NetApp.Migrations
{
    [DbContext(typeof(StravaDbContext))]
    partial class StravaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("MyMVC.NetApp.Models.Strava.StravaActivity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievementCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AverageHeartrate")
                        .HasColumnType("REAL");

                    b.Property<double?>("AverageSpeed")
                        .HasColumnType("REAL");

                    b.Property<double?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<bool>("Commute")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GearId")
                        .HasColumnType("TEXT");

                    b.Property<int>("KudosCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxHeartrate")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("REAL");

                    b.Property<int>("MovingTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Private")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SportType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDateLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalElevationGain")
                        .HasColumnType("REAL");

                    b.Property<bool>("Trainer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("StravaActivities");
                });

            modelBuilder.Entity("MyMVC.NetApp.Models.Strava.StravaAthlete", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AllTimeDistanceMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FollowerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FriendCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ftp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeasurementPreference")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Premium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileMediumUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileRawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatsRawJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StravaCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StravaUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Summit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StravaAthletes");
                });

            modelBuilder.Entity("MyMVC.NetApp.Models.Strava.StravaToken", b =>
                {
                    b.Property<long>("AthleteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AthleteId");

                    b.ToTable("StravaTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
